version: '3'

volumes:
  mysql_data:
    external: true

services:

  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entryPoints.web.address=:80"
    restart: always
    ports:
      - "0.0.0.0:8000:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - bookworm
      - nginx

  nginx:
    image: nginx:latest
    volumes:
      - ./serve:/usr/share/nginx/html/
      - ./bookworm/Bookworm-Vega/build:/usr/share/nginx/html/vega/
    labels:
      - traefik.http.routers.nginx.rule=HostRegexp(`localhost`)

  mariadb:
    image: mariadb:latest
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      # Put this in docker-compose.override.yml, with a secure password
      - MYSQL_ROOT_PASSWORD='<PASSWORD_IS_INSECURE>'

  bookworm:
    build:
      context: .
      dockerfile: ./compose/bookworm/Dockerfile
    environment:
      # Put this in docker-compose.override.yml, with a secure password
      - MYSQL_ROOT_PASSWORD='<PASSWORD_IS_INSECURE>'
    depends_on:
      - mariadb
    volumes:
      - ./corpus:/corpus
    # command: bookworm serve 
    command: gunicorn --bind 0.0.0.0:10012 bookworm:app
    labels:
      - traefik.http.routers.bookworm.rule=HostRegexp(`localhost`) && PathPrefix(`/cgi-bin`)
      - traefik.http.services.bookworm.loadbalancer.server.port=10012

