version: '3'

volumes:
  traefik_certs:
  mysql_data:
    external: true

services:

  traefik:
    build:
      context: .
      dockerfile: ./compose/traefik/Dockerfile
    image: traefik
    depends_on:
      - bookworm
      - nginx
    volumes:
      - traefik_certs:/etc/traefik/acme
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    command: traefik

  nginx:
    image: nginx:latest
    volumes:
      - ./serve:/usr/share/nginx/html/
      # Does this work?
      - ./bookworm/Bookworm-Vega/build:/usr/share/nginx/html/vega/

  mariadb:
    image: mariadb:latest
    volumes:
      - mysql_data:/var/lib/mysql
#    env_file:
#      - ./.envs/.production/.mariadb

  bookworm:
    build:
      context: .
      dockerfile: ./compose/bookworm/Dockerfile
    depends_on: 
      - mariadb
    volumes:
      - ./corpus:/corpus
    command: bookworm serve
